### ISSUE TITLE
In-place replacement with append/concat

### ISSUE THREAD

**Issue by fabien-zoccola** [ArkScript-lang/Ark#277]
**Is your feature request related to a problem? Please describe.**
Both `concat` and `append` return a new value instead of doing in-place replacement like expected. This adds the need to further wrap the call using `set` for said call to actually have an effect on the code.

**Describe the solution you'd like**
`concat` and `append` should replace the value in-place and not return anything. There should two new operators, `extends` (with an s, replaces `concat`) and `appendr` ("append and return", replaces `append`) that behave like the current `concat` and `append` functions

*`appendr` is still in discussion, feedback wanted on the keyword that seems ambiguous so far*

Example:
```ignorelang
(mut myList [1 2])

(concat myList [3 4])  # myList is now [1 2 3 4]
(extends myList [5 6])  # myList is left untouched, returned list is [1 2 5 6]

(append myList 8)  # myList is now [1 2 3 4 8]
(appendr myList 9)  # myList is left untouched, returned list is [1 2 3 4 9]
```

**Describe alternatives you've considered**
Instead of creating two new keywords, we could make `concat` and `append` also return the new value, as well as making in-place changes, although this seems to go against what this is issue is about, since list manipulation costs a lot of time *because of* the fact values are always returned by `concat` and `append`.

**Additional context**
Expected behaviour:
```ignorelang
(mut myList [])
(append myList 4)  # appends in-place
```
Current behaviour:
```lisp
(mut myList [])
(set myList (append myList 4))

**Comment by SuperFola** [comment]
>  since list manipulation costs a lot of time because of the fact values are always returned by concat and append.

I would also add that the current implementation is in a "pass by value" philosophy, thus append/concat not only return a list, they create new ones every time we use them

**Comment by Program132** [comment]
I agree it!

**Comment by SuperFola** [comment]
I've started working on a PoC and it's definitly doable.

1. Currently, I can handle const values, so things like
```lisp
(let a [1 2 3])
(append a 4)
(print a)
```
will fail at runtime => `can not modify a constant list using append`

2. Also, references are still internal and not exposed, so they aren't transfered upon copy
```lisp
(mut a [1 2 3])
(mut b a)
(append a 4)
(print a " " b)
```
`a` will be modified, but not `b` (it can be a mutable or constant, it won't be modified)

3. With this PoC, `append` and `concat` now returns `nil` because they modify the value in place.

4. Last but not least, references aren't transfered when calling functions:
```lisp
(mut a [1 2 3])
(let foo (fun (first last) {
    (print "before: " first)
    (concat first last)
    (print "after: " first)
}))
(print a)  # [1 2 3]
(foo a [4 5 6])  # before: [1 2 3]
                 # after: [1 2 3 4 5 6]
(print a)  # [1 2 3]
```
I feel like this last one is pretty important (even though I did nothing to have that in the language, that's due to how our scopes work, every value is copied), and I would like to know if it is what you would expect or not.

IMHO, the 4th statement should stay like this, otherwise this would be the root of many problems such as "my list was modified, but why and which function did it?", but if you have arguments against, feel free to comment.

**Comment by SuperFola** [comment]
For retro compatibility, I think in place mutation will be given the suffix `!`, so that existing programs won't break.

Do we all agree @ArkScript-lang/lead-developers ?
